### Find All attribute
GET http://localhost:3000/attribute
Content-Type: application/json


### Create attribute
POST http://localhost:3000/attribute
Content-Type: application/json

{
  "title": "СИЛА"
}


### Find One attribute
GET http://localhost:3000/attribute/1
Content-Type: application/json


### Update attribute
PATCH http://localhost:3000/attribute/1
Content-Type: application/json

{
  "title": "Carry"
}



### DELETE attribute
DELETE http://localhost:3000/attribute/11






